### ISSUE TITLE
Unexpected Different Behavior with every run

### ISSUE THREAD

**Issue by elkassar** [TestFX/TestFX#508] opened 2018-01-17 16:33 UTC
I have the following code:

`clickOn("_Tools");`
`clickOn(".menu-item");`
`clickOn("_Tools");`
`clickOn(".menu-item");`

First, the first line always clicks the menu before the menu "Tools". Why it doesn't click the menu "Tools" itself?
Second, the second line causes click to a different menu item every execution. What is wrong here so that the execution is not correcly predicted?

**Comment by brcolow** [comment] 2018-01-17 20:18
Could you show an example/test-case that demonstrates this (broken) behavior versus the expected behavior?

**Comment by seggcsont** [comment] 2018-01-19 07:38
I think the second one is working as designed.
ClickOn(String query) uses the queryVisibleNode method. It call queryAll on nodeQuery which gives back a Set of Nodes where the order is not fixed.
So it can happen that every execution it will pick up different menu-item.
You have to use more specific query.

**Comment by brcolow** [comment] 2018-01-19 20:35
Sorry, I had tagged the wrong issue for #510 - should have been #506  - I changed it now but I think the "brcolow added a commit that referenced this issue" stuff will stay.

**Comment by brcolow** [comment] 2018-10-06 03:33
Closing because the full reproducible test case was not provided.

**Closed by brcolow** 2018-10-06 03:33 UTC
Labels: s:waiting-for-response
