### ISSUE TITLE
Sample TestFx not working

### ISSUE THREAD

**Issue by integrys-net** [TestFX/TestFX#581] opened 2018-06-03 10:27 UTC
I'm trying TestFX by run the sample test in documentation, but this not work for second test case. Button on scene isn't clicked. Mouse click on coords(0,0), that is outside of test application window.

## Specifications

  - Version: TestFX 4.0.13-alpha with JUnit 5 binding
  - Platform: Java 8

**Comment by brcolow** [comment] 2018-06-05 09:15
What operating system are you running this on, and exactly what Java version (run `java -version` to get the full string).

**Comment by integrys-net** [comment] 2018-06-06 07:42
Thank you for reply @brcolow. Th eOS is Windows 10 build 1803, and java version used to run demo test, is JDK 1.8u172.

**Comment by brcolow** [comment] 2018-06-06 07:46
Do you know the DPI of your monitor? This could be https://bugs.openjdk.java.net/browse/JDK-8196031 if you are using hiDPI.

**Comment by integrys-net** [comment] 2018-06-06 14:08
Thank you for reply, i don't know that bug. I've readed now for the first time. My screen is HiDPI. The current dpi settings is 250%.

**Comment by kleopatra** [comment] 2018-10-02 09:42
the bug seems fixed in fx11 (the test case in the bug report passes, replacing the old robot api with the current) - the simple testfx example still fails

**Comment by brcolow** [comment] 2018-10-02 10:31
@kleopatra Which test-cases are you referring to? Which one passes and which one fails?

**Comment by kleopatra** [comment] 2018-10-02 10:40
sry, forgot to repeat it here: should_click_on_button() fails because the button isn't clicked

**Comment by kleopatra** [comment] 2018-10-02 13:41
okay, a day's debugging later (fx11 only): 

-  a stand-alone version of awt.Robot passes the test in the core bug report, both for fx controls and swing components, so don't know why the AWTRobotAdapter used by default in BaseRobotImp doesn't work correctly (should it?)
- GlassRobotAdapter is not yet adjusted to fx11 (as you probably know better than I do :) so it might be expected to blow - as it does with a java.lang.NoClassDefFoundError: com/sun/glass/ui/Robot
-as PoC: a quick hack of glassRobotAdapter that's parameterized on GlassRobot (nothing for production, of course) works fine. Drawback: couldn't find a way to inject a custom impl, so c&p'ed the whole stack from ApplicationTest down to FxRobotContext just to replace BaseRobotImp to use the hacked adapter.

That's for today, hungry now <g>

**Comment by brcolow** [comment] 2018-10-02 19:56
@kleopatra Would you mind detailing your operating system and Java version this is occurring on? We have a pretty extensive list of different CI machine configs and all tests are currently passing, so it's hard to debug this without full details and, even better, an actual failing test (even if it's really simple).

**Comment by kleopatra** [comment] 2018-10-03 08:35
you have the test case: https://github.com/TestFX/TestFX/wiki/Getting-Started :) And if it's really related to the core issue you mentioned JDK-8196031 (which I think it well might be), then you probably need a physical win10 machine one which the test case provided in the core bug fails for fx9/10 and passes for fx11. Nothing new to you, you robot expert :) Mine is a  plain laptop, running win10 with the latest update installed,  11' screen, full HD 1920x1080 with 150% scaling. 

On such a machine, the testfx sample test will fail for all all fx versions, even fx11 with the core fix (the latter no wonder, obviously, as it is not yet moved to fx11 and its public robot api ;) And it will - hopefully - pass for #606

**Comment by brcolow** [comment] 2018-10-03 08:46
Okay, I think I understand now. Indeed 150% is considered HiDPI and so the Windows robot was broken for some JavaFX versions and correspondingly that broke TestFX. Throwing some confusion in to the mix, however, is that AWT is the default robot on Windows so unless the `testfx.robot` property was explicitly set to `glass` I am not sure if these issues can be easily explained by [JDK-8196031](https://bugs.openjdk.java.net/browse/JDK-8196031). Regardless, if the issues you are seeing are no longer reproducible now that #606 is merged, that's certainly not a bad thing - I just am still unclear about the reasons why that would be.

**Comment by kleopatra** [comment] 2018-10-03 09:03
yeah, was puzzled at that as well. btw, I didn't test the merge (couldn't get testfx to compile, didn't put any effort into): instead I c&p'ed to inject a custom glassRobotAdapter with ripped out com.xx.Robot just to see that it helped (which it does). 

Regarding the new api (and just looking at your merged code): that one thing that I felt was missing is a way to destroy it. Not sure if that's publicly needed. Anyway, wondering whether your robotDestroy is working for PublicGlassRobotAdapter? It would be its peer (== underlying GlassRobot) that would need to be destroyed?

**Comment by brcolow** [comment] 2018-10-03 09:42
The difficult thing is knowing when destroy should be called. We are investigating adding a disposer mechanism to automatically call `destroy` so that native resources are cleaned up (when the platform's native robot implementation needs to do so) as part of [JDK-8207373](https://bugs.openjdk.java.net/browse/JDK-8207373).

Currently `robotDestroy` is public in `RobotAdapter` but IIRC it is not possible to get an instance of `RobotAdapter` from the TestFX API.

**Comment by kleopatra** [comment] 2018-10-05 12:41
FYI: verified tests are working fine with the new implementation - summarized at SO: https://stackoverflow.com/a/52665821/203657 

Thanks for your quick action :)

**Closed** 2018-10-06 02:56 UTC
