### ISSUE TITLE
TestFX not compatible with OpenJFX Monocle

### ISSUE THREAD

**Issue by Maxoudela** [TestFX/TestFX#364] opened 2017-02-07 14:10 UTC
Hi guys,

I wanted to use an upgraded version of Monocle because I have a lot of java.nio.BufferOverflowException

So I decided to import the latest one here:
```
<!-- https://mvnrepository.com/artifact/org.testfx/openjfx-monocle -->
<dependency>
    <groupId>org.testfx</groupId>
    <artifactId>openjfx-monocle</artifactId>
    <version>8u76-b04</version>
</dependency>
```

But then I have this exception : 
```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalAccessException: Class org.testfx.toolkit.impl.ApplicationLauncherImpl can not access a member of class com.sun.glass.ui.monocle.HeadlessPlatform with modifiers ""
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:161)
	at org.testfx.api.FxToolkit.waitForLaunch(FxToolkit.java:322)
	at org.testfx.api.FxToolkit.registerPrimaryStage(FxToolkit.java:131)
	at com.nellarmonia.installer.MatTestsIT.setupClass(MatTestsIT.java:71)
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: Class org.testfx.toolkit.impl.ApplicationLauncherImpl can not access a member of class com.sun.glass.ui.monocle.HeadlessPlatform with modifiers ""
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.initMonocleHeadless(ApplicationLauncherImpl.java:80)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.launch(ApplicationLauncherImpl.java:56)
	at org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupPrimaryStage$0(ToolkitServiceImpl.java:70)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:364)
	at org.testfx.util.WaitForAsyncUtils.lambda$async$1(WaitForAsyncUtils.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessException: Class org.testfx.toolkit.impl.ApplicationLauncherImpl can not access a member of class com.sun.glass.ui.monocle.HeadlessPlatform with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.Class.newInstance(Class.java:436)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.assignHeadlessPlatform(ApplicationLauncherImpl.java:101)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.initMonocleHeadless(ApplicationLauncherImpl.java:74)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.launch(ApplicationLauncherImpl.java:56)
	at org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupPrimaryStage$0(ToolkitServiceImpl.java:70)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:364)
	at org.testfx.util.WaitForAsyncUtils.lambda$async$1(WaitForAsyncUtils.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Is it normal? I'm using TestFX 4.0.5-alpha and using Monocle 8u20-b26, also putting this when launching the tests :
```
System.setProperty("testfx.robot", "glass");
        System.setProperty("testfx.headless", "true");
        System.setProperty("prism.order", "sw");
        System.setProperty("prism.text", "t2k");
        System.setProperty("headless.geometry", "1600x1200-64");

```

**Comment by brcolow** [comment] 2017-02-07 22:29
Which JDK (version) are you using when this happens?

**Comment by Maxoudela** [comment] 2017-02-08 08:54
Hi,
I'm using JDK 8u92

**Comment by brcolow** [comment] 2017-02-08 22:01
Can you provide results of:

`java --version`

and which OS you are running?

**Comment by evertvp** [comment] 2017-02-10 14:17
Can confirm this issue. Windows 10 with java 1.8.0_121.

It seems that TestFX tries to load `com.sun.glass.ui.monocle.headless.HeadlessPlatform`, but this class is found at `com.sun.glass.ui.monocle.HeadlessPlatform` in the 8u20-b26 version.

**Comment by Maxoudela** [comment] 2017-02-10 15:25
Hi, here is my version : 
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

I'm running on Windows 7 Pro 64 bits

**Comment by brcolow** [comment] 2017-02-10 20:43
I am confused because this should have been fixed in https://github.com/TestFX/TestFX/commit/606df553a578d99b4d05e83283bc94181d46ca6a .

**Comment by brcolow** [comment] 2017-02-14 00:49
@evertvp  @Maxoudela  Could you please try and see if https://github.com/TestFX/TestFX/pull/365 fixes the problem?

**Comment by Maxoudela** [comment] 2017-02-14 11:07
Well now I have this error:
```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.AbstractMethodError: com.sun.glass.ui.monocle.NativePlatform.createInputDeviceRegistry()Lcom/sun/glass/ui/monocle/input/InputDeviceRegistry;
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:284)
	at org.testfx.api.FxToolkit.waitForLaunch(FxToolkit.java:323)
	at org.testfx.api.FxToolkit.registerPrimaryStage(FxToolkit.java:132)
	at com.nellarmonia.installer.FiltersTestIT.setupClass(FiltersTestIT.java:73)
Caused by: java.lang.RuntimeException: java.lang.AbstractMethodError: com.sun.glass.ui.monocle.NativePlatform.createInputDeviceRegistry()Lcom/sun/glass/ui/monocle/input/InputDeviceRegistry;
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AbstractMethodError: com.sun.glass.ui.monocle.NativePlatform.createInputDeviceRegistry()Lcom/sun/glass/ui/monocle/input/InputDeviceRegistry;
	at com.sun.glass.ui.monocle.NativePlatform.getInputDeviceRegistry(NativePlatform.java:58)
	at com.sun.glass.ui.monocle.MonocleApplication.<init>(MonocleApplication.java:75)
	at com.sun.glass.ui.monocle.MonoclePlatformFactory.createApplication(MonoclePlatformFactory.java:43)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)

```

Using Monocle 8u76-b04 and your version of TestFX..

**Comment by brcolow** [comment] 2017-02-14 21:39
Thanks for testing that. I am really not sure why this is happening and perhaps more importantly why this does not occur on our Appveyor CI. Assistance/PRs are very welcome.

My hunch, based solely on the exception message, was that perhaps this error was occurring because `HeadlessPlatform` is not publicly visible.

**Comment by brcolow** [comment] 2017-02-15 06:46
I made one small change to try and fix this.

I tried bumping the monocle version to 8u76-b04 in #365 and the headless Appveyor build is working. I am not sure if it wasn't working before, however. Can you possibly test with the latest changes in #365? Thanks for your patience.

**Comment by brcolow** [comment] 2017-02-15 07:16
@Maxoudela I think that the new error appeared because of the mismatched versions between TestFX Monocle and the Monocle dependency. Can you please try the latest #365 again? The headless appveyor build appears to pass, but I don't know if it was broken before the constructor visibility changes.

**Comment by Maxoudela** [comment] 2017-02-15 09:06
I've just tested again and I still have the same error.

Can't you reproduce? It's stuck at 
`FxToolkit.registerPrimaryStage();`

and here are the properties I put in my file : 
```
static {
        System.setProperty("testfx.robot", "glass");
        System.setProperty("testfx.headless", "true");
        System.setProperty("prism.order", "sw");
        System.setProperty("prism.text", "t2k");
        System.setProperty("headless.geometry", "1600x1200-64");
    }
```

Maybe I'm doing something wrong idk

**Comment by brcolow** [comment] 2017-02-15 22:23
I am not able to reproduce, and as you can see the headless Appveyor CI build is successful. I also use TestFX in a couple different projects with Monocle 8u76-b04. Without being able to reproduce it is very hard for me to try and work on this :(.

**Comment by Maxoudela** [comment] 2017-02-16 13:44
Allright I will investigate and see why I have this error. Maybe I'm doing something wrong. Thanks for the time you spent searching on that issue. I will come back with more info and code. I'll try to reproduce it with an SSCCE

**Comment by Maxoudela** [comment] 2017-02-17 10:56
Allright I have made a very simple Maven Project with only one test here : https://github.com/Maxoudela/MonocleTest

When I run it with JDK 8u92, I have this exception :
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running BaseTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.167 sec <<< FAILURE! - in BaseTest
BaseTest  Time elapsed: 0.166 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.IllegalStateException: Monocle headless platform not found
	at org.testfx.util.WaitForAsyncUtils.waitFor(WaitForAsyncUtils.java:161)
	at org.testfx.api.FxToolkit.waitForLaunch(FxToolkit.java:264)
	at org.testfx.api.FxToolkit.registerPrimaryStage(FxToolkit.java:126)
	at BaseTest.setupClass(BaseTest.java:35)
Caused by: java.lang.IllegalStateException: Monocle headless platform not found
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.initMonocleHeadless(ApplicationLauncherImpl.java:75)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.launch(ApplicationLauncherImpl.java:54)
	at org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupPrimaryStage$53(ToolkitServiceImpl.java:70)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:363)
	at org.testfx.util.WaitForAsyncUtils.lambda$async$8(WaitForAsyncUtils.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.sun.glass.ui.monocle.headless.HeadlessPlatform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.assignHeadlessPlatform(ApplicationLauncherImpl.java:98)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.initMonocleHeadless(ApplicationLauncherImpl.java:72)
	at org.testfx.toolkit.impl.ApplicationLauncherImpl.launch(ApplicationLauncherImpl.java:54)
	at org.testfx.toolkit.impl.ToolkitServiceImpl.lambda$setupPrimaryStage$53(ToolkitServiceImpl.java:70)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:363)
	at org.testfx.util.WaitForAsyncUtils.lambda$async$8(WaitForAsyncUtils.java:88)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

If you could fork it and build it and confirm you don't see any errors.

**Comment by brcolow** [comment] 2017-02-17 20:27
I see that your TestFX version is `4.0.4-alpha` - please try `4.0.5-alpha`.

**Comment by brcolow** [comment] 2017-02-17 22:16
Okay, so, I forked your repository and made a couple changes:

https://github.com/brcolow/MonocleTest

Then I checked out #364 locally and bumped the version in `gradle.properties` to `4.0.6-alpha` and then ran
`./gradlew publishToMavenLocal`

Then I tried to build MonocleTest with `mvn test` and the results were successful.

Trying to build MonocleTest on TestFX master does indeed cause an error, but #364 fixes it for me.

**Comment by Maxoudela** [comment] 2017-02-20 12:59
Allright I was able to build myself with the explanations you gave!

So I think we can consider this issue fixed when your pull request will be merged. Then I'll wait for the 4.0.6 version! 
Thank you very much for the time you took analysing my issue. Much appreciated!

**Closed** 2017-02-20 20:21 UTC
