### ISSUE TITLE
Regression since v4.0.12-alpha : moveTo do not move mouse at position specified by robotContext().setPointPosition

### ISSUE THREAD

**Issue by dweil** [TestFX/TestFX#561] opened 2018-04-19 14:36 UTC
## Expected Behavior

robotContext().setPointPosition(Pos.BOTTOM_CENTER)
moveTo(mynode)

should move to bottom of "mynode"

## Actual Behavior

always move to center of "mynode"

(the method clickOn() behave correctly)

## Specifications

  - Version: 4.012-13
  - Platform: Windows 10, jdk1.8.0_162

**Comment by brcolow** [comment] 2018-04-19 22:48
It would be a tremendous help if you could [bisect](https://git-scm.com/docs/git-bisect) the commit. If you can't do that, could you construct a test-case that succeeds before `4.0.12-alpha` and fails after?

**Comment by dweil** [comment] 2018-04-22 21:28
Unfortunately, I did'nt manage to compile previous version of TestFX (only master branch dit compile with my Netbeans IDE)...but i'm not familiar yet with gradle.

Anyway, here's the test case that fail after 4.0.12-alpha:
`/*
 * Copyright 2013-2014 SmartBear Software
 * Copyright 2014-2018 The TestFX Contributors
 *
 * Licensed under the EUPL, Version 1.1 or - as soon they will be approved by the
 * European Commission - subsequent versions of the EUPL (the "Licence"); You may
 * not use this work except in compliance with the Licence.
 *
 * You may obtain a copy of the Licence at:
 * http://ec.europa.eu/idabc/eupl.html
 *
 * Unless required by applicable law or agreed to in writing, software distributed
 * under the Licence is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the Licence for the
 * specific language governing permissions and limitations under the Licence.
 */
package org.testfx.robot.impl;

import javafx.scene.input.MouseButton;

import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.testfx.framework.junit.TestFXRule;
import org.testfx.robot.ClickRobot;
import org.testfx.robot.Motion;
import org.testfx.robot.MouseRobot;
import org.testfx.robot.MoveRobot;
import org.testfx.robot.SleepRobot;
import org.testfx.service.query.PointQuery;

import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.verifyZeroInteractions;

public class ClickRobotImplTest {

    @Rule
    public TestFXRule testFXRule = new TestFXRule();

    ClickRobot clickRobot;
    MouseRobot mouseRobot;
    MoveRobot moveRobot;
    SleepRobot sleepRobot;

    @Before
    public void setup() {
        mouseRobot = mock(MouseRobot.class);
        moveRobot = mock(MoveRobot.class);
        sleepRobot = mock(SleepRobot.class);
        clickRobot = new ClickRobotImpl(mouseRobot, moveRobot, sleepRobot);
    }

    @Test
    public void clickOn_with_primary_mouse_button() {
        // when:
        clickRobot.clickOn(MouseButton.PRIMARY);

        // then:
        verify(mouseRobot, times(1)).pressNoWait(eq(MouseButton.PRIMARY));
        verify(mouseRobot, times(1)).release(eq(MouseButton.PRIMARY));
        verifyNoMoreInteractions(mouseRobot);
        verifyZeroInteractions(moveRobot, sleepRobot);
    }

    @Test
    public void clickOn_with_primary_and_secondary_mouse_buttons() {
        // when:
        clickRobot.clickOn(MouseButton.PRIMARY, MouseButton.SECONDARY);

        // then:
        verify(mouseRobot, times(1)).pressNoWait(
            eq(MouseButton.PRIMARY), eq(MouseButton.SECONDARY)
        );
        verify(mouseRobot, times(1)).release(
            eq(MouseButton.PRIMARY), eq(MouseButton.SECONDARY)
        );
        verifyNoMoreInteractions(mouseRobot);
        verifyZeroInteractions(moveRobot, sleepRobot);
    }

    @Test
    public void clickOn_with_pointQuery_and_primary_button() {
        // given:
        PointQuery pointQuery = mock(PointQuery.class);

        // when:
        clickRobot.clickOn(pointQuery, MouseButton.PRIMARY);

        // then:
        verify(moveRobot, times(1)).moveTo(eq(pointQuery), eq(Motion.DEFAULT));
        verify(mouseRobot, times(1)).pressNoWait(eq(MouseButton.PRIMARY));
        verify(mouseRobot, times(1)).release(eq(MouseButton.PRIMARY));
        verifyNoMoreInteractions(moveRobot, mouseRobot);
        verifyZeroInteractions(sleepRobot);
    }

    @Test
    public void doubleClickOn_with_primary_mouse_button() {
        // when:
        clickRobot.doubleClickOn(MouseButton.PRIMARY);

        // then:
        verify(mouseRobot, times(2)).pressNoWait(eq(MouseButton.PRIMARY));
        verify(mouseRobot, times(2)).release(eq(MouseButton.PRIMARY));
        verify(sleepRobot, times(1)).sleep(anyLong());
        verifyNoMoreInteractions(mouseRobot, sleepRobot);
        verifyZeroInteractions(moveRobot);
    }

    @Test
    public void doubleClickOn_with_primary_and_secondary_mouse_buttons() {
        // when:
        clickRobot.doubleClickOn(MouseButton.PRIMARY, MouseButton.SECONDARY);

        // then:
        verify(mouseRobot, times(2)).pressNoWait(
            eq(MouseButton.PRIMARY), eq(MouseButton.SECONDARY)
        );
        verify(mouseRobot, times(2)).release(
            eq(MouseButton.PRIMARY), eq(MouseButton.SECONDARY)
        );
        verify(sleepRobot, times(1)).sleep(anyLong());
        verifyNoMoreInteractions(mouseRobot, sleepRobot);
        verifyZeroInteractions(moveRobot);
    }

    @Test
    public void doubleClickOn_with_pointQuery_and_primary_button() {
        // given:
        PointQuery pointQuery = mock(PointQuery.class);

        // when:
        clickRobot.doubleClickOn(pointQuery, MouseButton.PRIMARY);

        // then:
        verify(moveRobot, times(1)).moveTo(eq(pointQuery), eq(Motion.DEFAULT));
        verify(mouseRobot, times(2)).pressNoWait(eq(MouseButton.PRIMARY));
        verify(mouseRobot, times(2)).release(eq(MouseButton.PRIMARY));
        verify(sleepRobot, times(1)).sleep(anyLong());
        verifyNoMoreInteractions(moveRobot, mouseRobot, sleepRobot);
    }

}
`

**Comment by brcolow** [comment] 2018-04-22 22:06
Thanks very much, that will be enough for me to get started. I'll try and look into it in the next few days.

**Comment by brcolow** [comment] 2018-04-22 23:09
So I am trying to bisect this issue but for me (on Windows 10) the test fails on master, 4.0.13-alpha, 4.0.12-alpha, 4.0.11-alpha, and 4.0.10-alpha so I am not sure this is a regression. That's as far as I can go back without getting git related conflict headaches. I am not saying that this is not a bug, but just saying I can't get it to ever work historically. I will have to think about what it is the test is trying to demonstrate (I am a little confused about that) and if it is working as intended or if there is indeed a bug.

If you are trying to move to a certain position on a node, perhaps you could use:

` FxRobot#moveTo(Node node, Pos offsetReferencePos, Point2D offset, Motion motion)` and use `(0,0)` for the offset? From very quickly looking at the code, it seems that pointPosition is only used in the `point` related methods and therefore won't have any effect in the other methods (`moveTo`, `clickOn`, etc.).

**Comment by dweil** [comment] 2018-04-23 10:45
Strange, I'm always on windows10. I'm on jdk1.8.9_162. Do you have the same version of java ?
On my computer, it is clearly on releases  4.0.12-alpha or later (I'm not compiling source code, juste retreaving  code from Maven Repository). Here are the dependancy I have added in my maven file:
      ```
<dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-core</artifactId>
            <version>4.0.11-alpha</version>

            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testfx</groupId>
            <artifactId>testfx-junit</artifactId>
            <version>4.0.11-alpha</version>
            <scope>test</scope>
        </dependency>
```

I can't find the method FxRobot#moveTo(Node node, Pos offsetReferencePos, Point2D offset, Motion motion). Is it a public method ?

**Comment by brcolow** [comment] 2018-04-23 20:02
I was testing on Java 10. Sorry, I should have made that clear. [Here](https://github.com/TestFX/TestFX/blob/0eef18d9123ebc0f95522f5a176363c4add36088/subprojects/testfx-core/src/main/java/org/testfx/api/FxRobot.java#L908) is the method I mentioned.

**Comment by brcolow** [comment] 2018-04-23 22:15
I am having trouble reproducing it on my PC...if you could do a git bisect to narrow down the offending commit we should be able to fix this. Because I can't reproduce on my PC, it is not possible for me to bisect the commit.

One way to do this is to create a new branch on your local git repo of your TestFX fork, copy `Issue561.java` from https://github.com/TestFX/TestFX/pull/565, and put it in git's stash (`git stash`). Then, start a git [bisect](https://git-scm.com/docs/git-bisect) marking the current commit as bad and `v4.0.11-alpha` as good. It will then iterate through the bisected commits. Each time, pop the stash so that `Issue561.java` is added to the staging area. Then, use gradle to run just that test using `.\gradlew :testfx-core:test --tests *Issue561`. Mark if it passes or fails (using git bisect) and continue on.

**Comment by brcolow** [comment] 2018-10-06 03:30
This should be fixed on latest master.

**Closed by brcolow** 2018-10-06 03:30 UTC
